"""feat-revision

Revision ID: cbd5f06cfb68
Revises: 
Create Date: 2026-02-03 22:37:43.597014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbd5f06cfb68'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_revisions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_revision_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_document_revisions_parent_revision_id_document_revisions'), 'document_revisions', ['parent_revision_id'], ['id'])

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_revision_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_documents_current_revision_id_document_revisions'), 'document_revisions', ['current_revision_id'], ['id'])

    with op.batch_alter_table('file_tasks', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_file_tasks_file_id_files'), 'files', ['file_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_users_avatar_id_files'), 'files', ['avatar_id'], ['id'])

    # ### end Alembic commands ###
    
    # Data migration: Set current_revision_id for all documents that don't have one
    # For each document, set the current_revision to the latest revision by created_time
    connection = op.get_bind()
    
    # Get all documents without a current_revision_id
    documents_without_current = connection.execute(
        sa.text("SELECT id FROM documents WHERE current_revision_id IS NULL")
    ).fetchall()
    
    # For each document, find the latest revision and set it as current
    for doc in documents_without_current:
        doc_id = doc[0]
        latest_revision = connection.execute(
            sa.text(
                "SELECT id FROM document_revisions "
                "WHERE document_id = :doc_id "
                "ORDER BY created_time DESC LIMIT 1"
            ),
            {"doc_id": doc_id}
        ).fetchone()
        
        if latest_revision:
            revision_id = latest_revision[0]
            connection.execute(
                sa.text(
                    "UPDATE documents SET current_revision_id = :revision_id "
                    "WHERE id = :doc_id"
                ),
                {"revision_id": revision_id, "doc_id": doc_id}
            )
    
    connection.commit()


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_avatar_id_files'), type_='foreignkey')

    with op.batch_alter_table('file_tasks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_file_tasks_file_id_files'), type_='foreignkey')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_documents_current_revision_id_document_revisions'), type_='foreignkey')
        batch_op.drop_column('current_revision_id')

    with op.batch_alter_table('document_revisions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_document_revisions_parent_revision_id_document_revisions'), type_='foreignkey')
        batch_op.drop_column('parent_revision_id')

    # ### end Alembic commands ###
