"""fix delimiter injection

Revision ID: e09c3ecf8f0a
Revises: 50df72915860
Create Date: 2026-04-06 01:46:11.263975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e09c3ecf8f0a'
down_revision: Union[str, Sequence[str], None] = '50df72915860'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ip_login_security',
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('last_attempt', sa.DateTime(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ip_address', name=op.f('pk_ip_login_security'))
    )
    with op.batch_alter_table('login_security', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('ip_address', sa.String(length=45), nullable=False))
        batch_op.create_index(batch_op.f('ix_login_security_ip_address'), ['ip_address'], unique=False)
        batch_op.drop_column('identifier')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_security', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identifier', sa.VARCHAR(length=128), nullable=False))
        batch_op.drop_index(batch_op.f('ix_login_security_ip_address'))
        batch_op.drop_column('ip_address')
        batch_op.drop_column('username')

    op.drop_table('ip_login_security')
    # ### end Alembic commands ###
