"""optimize database structure

Revision ID: e805605cbb30
Revises: 436b0d3452b6
Create Date: 2026-02-20 23:05:18.215004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e805605cbb30'
down_revision: Union[str, Sequence[str], None] = '436b0d3452b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_documents_folder_id_folders'), 'folders', ['folder_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('file_tasks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_file_tasks_file_id_files'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_file_tasks_file_id_files'), 'files', ['file_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_folders_parent_id_folders'), 'folders', ['parent_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('group_permissions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_group_permissions_group_name_user_groups'), 'user_groups', ['group_name'], ['group_name'], ondelete='CASCADE')

    with op.batch_alter_table('keyrings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_keyrings_username_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_keyrings_username_users'), 'users', ['username'], ['username'], ondelete='CASCADE')

    with op.batch_alter_table('user_memberships', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_user_memberships_group_name_user_groups'), 'user_groups', ['group_name'], ['group_name'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_user_memberships_username_users'), 'users', ['username'], ['username'], ondelete='CASCADE')

    with op.batch_alter_table('user_permissions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_user_permissions_username_users'), 'users', ['username'], ['username'], ondelete='CASCADE')

    with op.batch_alter_table('userblock_entries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_userblock_entries_username_users'), 'users', ['username'], ['username'], ondelete='CASCADE')

    with op.batch_alter_table('userblock_sub_entries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_userblock_sub_entries_parent_id_userblock_entries'), 'userblock_entries', ['parent_id'], ['block_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userblock_sub_entries', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_userblock_sub_entries_parent_id_userblock_entries'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'userblock_entries', ['parent_id'], ['block_id'])

    with op.batch_alter_table('userblock_entries', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_userblock_entries_username_users'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['username'], ['username'])

    with op.batch_alter_table('user_permissions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_permissions_username_users'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['username'], ['username'])

    with op.batch_alter_table('user_memberships', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_memberships_username_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_user_memberships_group_name_user_groups'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['username'], ['username'])
        batch_op.create_foreign_key(None, 'user_groups', ['group_name'], ['group_name'])

    with op.batch_alter_table('keyrings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_keyrings_username_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_keyrings_username_users'), 'users', ['username'], ['username'])

    with op.batch_alter_table('group_permissions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_group_permissions_group_name_user_groups'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_groups', ['group_name'], ['group_name'])

    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_folders_parent_id_folders'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'folders', ['parent_id'], ['id'])

    with op.batch_alter_table('file_tasks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_file_tasks_file_id_files'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_file_tasks_file_id_files'), 'files', ['file_id'], ['id'])

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_documents_folder_id_folders'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'folders', ['folder_id'], ['id'])

    # ### end Alembic commands ###
